name: Push PDFs to Orphan Branch

on:
  push:
    branches:
      - main

jobs:
  push-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout orphan branch
        run: |
          git fetch origin pdf
          git checkout pdf

      - name: Copy PDFs from main
        run: |
          git checkout main -- '*.pdf'

      - name: Add and commit PDFs
        run: |
          git add *.pdf
          git commit -m "Update PDFs from main branch" || echo "No changes to commit"

      - name: Push to orphan branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin pdf
